name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 14.6.0
    
    - name: Install global dependencies
      run: yarn global add @angular/cli @nestjs/cli nx typescript less

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
